---
- name: Get RHEL OS Release
  hosts: all

  tasks:
  - name: "Read RHEL File Content"
    shell: |
      cat /etc/redhat-release
    register: file_content
  - name: "Print the file content"
    debug:
      msg: "{{ file_content }}"
